const Blog = require("../models/blogModel");

// GET all blogs (public)
const getBlogs = async (req, res) => {
  try {
    const blogs = await Blog.find().sort({ createdAt: -1 });
    res.json(blogs);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// GET single blog by slug
const getBlogBySlug = async (req, res) => {
  try {
    const blog = await Blog.findOne({ slug: req.params.slug });

    if (!blog) return res.status(404).json({ message: "Blog not found" });

    res.json(blog);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// CREATE blog (admin)
const createBlog = async (req, res) => {
  try {
    const { title, content, category } = req.body;

    if (!title || !content) {
      return res.status(400).json({
        message: "Title and content are required"
      });
    }

    const blog = new Blog({
      title,
      content,
      category
    });

    await blog.save(); // slug auto-generated by pre-save

    res.status(201).json({
      message: "Blog created successfully",
      blog
    });

  } catch (error) {
    console.error("CREATE BLOG ERROR:", error);
    res.status(500).json({ error: error.message });
  }
};

// UPDATE blog
const updateBlog = async (req, res) => {
  try {
    const { title, content, category } = req.body;

    if (!title || !content) {
      return res.status(400).json({
        message: "Title and content are required"
      });
    }

    const slug =
      title.toLowerCase().replace(/ /g, "-") + "-" + Date.now();

    const updatedBlog = await Blog.findByIdAndUpdate(
      req.params.id,
      {
        title,
        content,
        category,
        slug
      },
      { new: true }
    );

    res.json({
      message: "Blog updated successfully",
      blog: updatedBlog
    });

  } catch (error) {
    console.error("UPDATE BLOG ERROR:", error);
    res.status(500).json({ error: error.message });
  }
};

// DELETE blog
const deleteBlog = async (req, res) => {
  try {
    await Blog.findByIdAndDelete(req.params.id);
    res.json({ message: "Blog deleted" });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

module.exports = { getBlogs, getBlogBySlug, createBlog, updateBlog, deleteBlog}